/*
 * Home.java
 *
 * Created on __DATE__, __TIME__
 */

package views;

/**
 *
 * @author  __USER__
 */
public class Home extends javax.swing.JFrame {

	models.HomeManagement homeManagement = new models.HomeManagement();

	/**
	 * 
	 */
	private static final long serialVersionUID = 1371573529365092976L;

	/** Creates new form Home */
	public Home() {
		initComponents();
		initFunctionality();
	}

	public void exitApp() {
		homeManagement.exitApp(subFileMenu);
	}

	public void categoriesManagement() {
		homeManagement.categoriesManagement(categoriesListMenu);
	}

	public void articlesManagement() {
		homeManagement.articlesManagement(articlesListMenu);
	}

	public void about() {
		homeManagement.about(subAboutMenu);
	}

	public void initFunctionality() {
		setLocationRelativeTo(null);
		exitApp();
		categoriesManagement();
		articlesManagement();
		about();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		backgroundLabel = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		subFileMenu = new javax.swing.JMenuItem();
		categoriesManagementMenu = new javax.swing.JMenu();
		categoriesListMenu = new javax.swing.JMenuItem();
		articlesManagementMenu = new javax.swing.JMenu();
		articlesListMenu = new javax.swing.JMenuItem();
		usersManagementMenu = new javax.swing.JMenu();
		usersListMenu = new javax.swing.JMenuItem();
		aboutMenu = new javax.swing.JMenu();
		subAboutMenu = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setTitle("Home");
		setResizable(false);

		backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/assets/background.png"))); // NOI18N

		fileMenu.setText("File");

		subFileMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_C,
				java.awt.event.InputEvent.SHIFT_MASK
						| java.awt.event.InputEvent.CTRL_MASK));
		subFileMenu.setText("Close");
		fileMenu.add(subFileMenu);

		jMenuBar1.add(fileMenu);

		categoriesManagementMenu.setText("Categories Management");

		categoriesListMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_C,
				java.awt.event.InputEvent.ALT_MASK
						| java.awt.event.InputEvent.CTRL_MASK));
		categoriesListMenu.setText("Categories List");
		categoriesManagementMenu.add(categoriesListMenu);

		jMenuBar1.add(categoriesManagementMenu);

		articlesManagementMenu.setText("Articles Management");

		articlesListMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_A,
				java.awt.event.InputEvent.SHIFT_MASK
						| java.awt.event.InputEvent.CTRL_MASK));
		articlesListMenu.setText("Articles List");
		articlesManagementMenu.add(articlesListMenu);

		jMenuBar1.add(articlesManagementMenu);

		usersManagementMenu.setText("Users Management");

		usersListMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_U,
				java.awt.event.InputEvent.SHIFT_MASK
						| java.awt.event.InputEvent.CTRL_MASK));
		usersListMenu.setText("Users List");
		usersManagementMenu.add(usersListMenu);

		jMenuBar1.add(usersManagementMenu);

		aboutMenu.setText("About !");

		subAboutMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_A,
				java.awt.event.InputEvent.ALT_MASK
						| java.awt.event.InputEvent.CTRL_MASK));
		subAboutMenu.setText("About !");
		aboutMenu.add(subAboutMenu);

		jMenuBar1.add(aboutMenu);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				backgroundLabel));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				backgroundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 602,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenu aboutMenu;
	private javax.swing.JMenuItem articlesListMenu;
	private javax.swing.JMenu articlesManagementMenu;
	private javax.swing.JLabel backgroundLabel;
	private javax.swing.JMenuItem categoriesListMenu;
	private javax.swing.JMenu categoriesManagementMenu;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem subAboutMenu;
	private javax.swing.JMenuItem subFileMenu;
	private javax.swing.JMenuItem usersListMenu;
	private javax.swing.JMenu usersManagementMenu;
	// End of variables declaration//GEN-END:variables

}